Milestone 2: User interface
AbdumurodovaZulfizar/Tic-Tac-Toe-Game pull request #2
Opened 2021-05-10 21:11 UTC by ad9311

### Milestone 2: User interface
In this PR we have created a mob preview of what the game will look like.
- It takes input from the two users
- does something according to input

2021-05-10 22:02 UTC, henatan99 requested changes
# Changes Requested :recycle: 

### Hi there, nice job so far :+1:. There are a few things to work on before your project gets approved. 

## To Highlight 
- Nice project structure
- Nice PR summary and commit messages 
- Proper use of puts and gets.chomp in the user interface 
## To Improve 
- user-input should be validated and an invalid or empty user name should not be allowed. Please look at the attached screenshot for reference. 
![Screenshot from 2021-05-11 02-28-01](https://user-images.githubusercontent.com/64894927/117726924-faebf580-b1ef-11eb-8a34-53f652652d5a.png)

- Your code needs to be refactored. You have an unnecessarily repeated piece of code. Follow DRY (don't repeat yourself). Please see inline comments for detailed explanations. 

### Kindly make the requested changes and submit for another review. 

Should you have any queries, you can find me via:
[LinkedIn](https://www.linkedin.com/in/henok-mekonnen/) |  [Twitter](https://twitter.com/henatan99) | Henok Mekonnen on Slack

2021-05-10 22:02 UTC, henatan99 commented on bin/main.rb
> +  end
This piece of code is repeated a lot of times. That is not a good programming way. For this user interface, you can just encapsulate this piece of code in a while loop. For example,
``` 
while !win_condition? | | !draw_condition?
     system 'clear'
     puts square
     puts "it's #{name}'s turn to play."      # here I put name b/c it can be assigned to name1 and name 2 alternatively
     puts 'Please select an available cell from the board!'
     number = gets.chomp
     ele = number.to_i
     until (1..9).any?(ele)
       puts 'Invalid move. Please enter a number between 1-9' unless (1..9).any?(ele)
       number = gets.chomp
       ele = number.to_i
     end
     # you can write win_condition here
     # You can write draw_condition here

     # assign name for the next turn 
end 
```

2021-05-10 22:02 UTC, henatan99 commented on bin/main.rb
> +  end
Unnecessarily repeated code

2021-05-10 22:02 UTC, henatan99 commented on bin/main.rb
> +  end
Unnecessarily repeated code

2021-05-10 22:02 UTC, henatan99 commented on bin/main.rb
> +  end
Unnecessarily repeated code

2021-05-10 22:02 UTC, henatan99 commented on bin/main.rb
> +end
Unnecessarily repeated code

2021-05-11 15:44 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello, @AbdumurodovaZulfizar @ad9311, good job on this milestone! 🔥 

You worked hard in all the instructions that the previous Code Reviewer gives you👍🏽 

![awesome-job](https://user-images.githubusercontent.com/60631456/117845073-d884c700-b245-11eb-9401-73217cea80e9.gif)


Now you can merge this branch 🚀 

You can contact me on slack if you have any questions, just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

2021-05-11 15:46 UTC, merged